### ISSUE TITLE
Node

### ISSUE THREAD

**Issue by JetF0x** [piratepowered/piratepowered.ga#1]
Which version of node are you using to install this?

**Comment by JetF0x** [comment]
Nevermind got it kindof, just having some other issues.

undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\admin\Documents\piratepowered.ga-master\index.js:493:40
    at C:\Users\admin\Documents\piratepowered.ga-master\node_modules\ps-node\lib\index.js:150:13
    at ChildProcess.<anonymous> (C:\Users\admin\Documents\piratepowered.ga-master\node_modules\ps-node\lib\index.js:62:13)
    at ChildProcess.emit (events.js:219:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
